PACKAGE_NAME=ollash

.PHONY: install uninstall reinstall run test clean package publish

install:
	pip install .

uninstall:
	pip uninstall -y $(PACKAGE_NAME)

reinstall: uninstall install

run:
	ollash $(ARGS)

test:
	python -m unittest discover tests/

package:
	python setup.py sdist bdist_wheel

publish: package
	twine upload dist/*

clean:
	rm -rf build dist *.egg-info
